FROM golang:1.22 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /oma-server ./cmd/oma-server

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=build /oma-server /app/oma-server
EXPOSE 8787
ENTRYPOINT ["/app/oma-server"]
